#!/usr/bin/env bash
# veriseal demo — seal → verify INTACT → tamper → verify TAMPERED → inspect
#
# Sample: SYNTHETIC MCAP (demo/sample.mcap generated by demo/make_sample.py)
# Run from the repo root: bash demo/demo.sh

set -euo pipefail
# Prevent Git Bash on Windows from converting /topic paths to Windows paths
export MSYS_NO_PATHCONV=1
cd "$(dirname "$0")/.."

SAMPLE=demo/sample.mcap
SEAL=demo/sample.seal.json
TAMPERED=demo/tampered.mcap

echo "========================================"
echo " 0. Generate synthetic sample MCAP"
echo "========================================"
python demo/make_sample.py

echo
echo "========================================"
echo " 1. Seal (no anchor for fast demo)"
echo "========================================"
veriseal seal "$SAMPLE" --no-anchor --out "$SEAL"

echo
echo "========================================"
echo " 2. Verify — expect INTACT"
echo "========================================"
veriseal verify "$SAMPLE" "$SEAL"

echo
echo "========================================"
echo " 3. Tamper: flip byte 0 of first /pose payload"
echo "========================================"
python demo/tamper.py "$TAMPERED"

echo
echo "========================================"
echo " 4. Verify tampered copy — expect TAMPERED"
echo "========================================"
veriseal verify "$TAMPERED" "$SEAL" || true   # exit 1 is expected

echo
echo "========================================"
echo " 5. Inspect incident window (+1s to +4s)"
echo "========================================"
veriseal inspect "$SAMPLE" \
    --from 2025-06-16T00:00:01Z \
    --to   2025-06-16T00:00:04Z \
    --topic /pose

echo
echo "Done."
